### ISSUE TITLE
Problems with special characters and "code" block

### ISSUE THREAD

**Issue by spinal-tap** [bigin/Scriptor#13]
Hi,
I started making personal "wiki" site with your script and when I want to insert characters like **°**, **–**, **×**, and letter **š** in code block they are displayed like `&deg;, &ndash;, &times;, &scaron;`
But it is strange that when I go to preview everything is normal. Site is on default theme, and in configuration I just renamed site.
Can you reproduce that behaviour? I don't know what's the problem. Thanks

Screenshots:
**1. in editor:**
![image](https://user-images.githubusercontent.com/37048939/97046751-240ca780-1578-11eb-997e-47e28af77f2b.png)
**2. preview:**
![image](https://user-images.githubusercontent.com/37048939/97046834-4b637480-1578-11eb-8968-cf44d7d017f5.png)
**3. on site**
![image](https://user-images.githubusercontent.com/37048939/97046915-6930d980-1578-11eb-9983-7747b7034c51.png)

**Comment by bigin** [comment]
Set the blab variable to `true` in the `custom.scriptor-config.php file`. This should fix the problem.
```php
/**
 * Enable HTML tags in page content
 * 
 * @var bool
 */
'allowHtmlOutput' => true,
```

More info: https://scriptor-cms.info/documentation/basics/website-configuration/

**Comment by bigin** [comment]
You can also wrap the output in your template with the `htmlspecialchars_decode()`:
```php
<div id="content" role="article">
  <?php echo htmlspecialchars_decode($site->render('content')); ?>
</div>
```

**Comment by spinal-tap** [comment]
`allowHtmlOutput` solution didn't work, but 2nd solution with `htmlspecialchars_decode` solved problem.
I think 2nd solution worked because of the "state" in which characters are saved in 1.items.php file
![image](https://user-images.githubusercontent.com/37048939/97051878-499daf00-1580-11eb-8630-41e4873022a2.png)

Thanks for your help 🥇

**Comment by bigin** [comment]
Alternatively, if you do not want to change the default template, just clone it and rename or use this hook in your custom.scriptor-config.php file:
```php
'hooks' => [
  'Site::afterRender' => [
    [
      'method' => function($e) {
        $e->return = htmlspecialchars_decode($e->return);
      }
    ]
  ],
],
```
you are welcome.

**Comment by spinal-tap** [comment]
Your little CMS is awesome, and your support also 👍
