### ISSUE TITLE
Logo contribution 

### ISSUE THREAD

**Issue by batarian71** [bigin/Scriptor#2]
Hello. I am a graphic designer. I want to volunteer support for open source projects. If you want, I can design a logo for you. What do you say? Also tell me if you want something. I can design.

**Comment by bigin** [comment]
Yes of course, take over graphic design work related to this project, if you're good at this. If your work is good, I would include a link to your website in the project references (if you like). 
Thank you.

**Comment by bigin** [comment]
The project has a logo, but it is not very well designed. You can see it when you are logged into the admin.

**Comment by batarian71** [comment]
I designed an icon logo. I hope you like it. Which one did you like?

![untitled-1](https://user-images.githubusercontent.com/36008612/41824539-584bf5d0-781a-11e8-81d3-e210eb78fad9.jpg)

**Comment by bigin** [comment]
Hmm.. not really, none of them. Here are several issues: I think it should be a horizontally shaped logo. Currently, the Scriptor's admin design is orientated towards the horizontal forms and I would only change that if the logo would be really amazing. 
Typography must always be visually balanced with the symbol of the logo. The symbol currently dominates the logo and the typography seems small and insignificant...

**Comment by bigin** [comment]
Take your time or just leave it, a good design takes a lot of time.
